strings_bin_converter.py C:\Games\MedievalII\data\text\battle.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\battle_descriptions.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\battle_ed.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\battle_event_subtitles.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\campaign_descriptions.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\climates.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\cursor_action_tooltips.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\diplomacy.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\diplomacy_speech.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\event_strings.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\event_titles.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\expanded.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_advice.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_ancillaries.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_buildings.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_prologue.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_units.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\export_vnvs.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\FactionIntroSubTitles.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\historic_battles_subtitles.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\imperial_campaign_regions_and_settlement_names.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\menu_english.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\missions.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\names.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\norman_prologue_regions_and_settlement_names.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\prebattle_speeches_subtitles.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\quotes.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\rebel_faction_descr.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\religions.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\shared.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\shortcut.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\strat.txt
strings_bin_converter.py C:\Games\MedievalII\data\text\tooltips.txt
del *.bin 
exit